#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service functions kopano

PROCESS_NAME="kopano-search"
check_container_initialized
liftoff

rm -rf /var/run/kopano/search.pid

wait_for_server search
sleep 3

print_info "Starting Kopano Search"
kopano-search "${SEARCH_ADDITIONAL_ARGS}"
