#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service functions kopano

PROCESS_NAME="kopano-server"
check_container_initialized
liftoff

rm -rf /var/run/kopano/server.pid

print_info "Starting Kopano Server"
kopano-server "${SERVER_ADDITIONAL_ARGS}"
