#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service functions kopano

PROCESS_NAME="kopano-ical"
check_container_initialized
liftoff

wait_for_server
sleep 3

print_info "Starting Kopano ICAL Server"
kopano-ical "${ICAL_ADDITIONAL_ARGS}"
