#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service functions kopano
PROCESS_NAME="kopano-monitor"
check_container_initialized
liftoff

rm -rf /var/run/kopano/monitor.pid

wait_for_server monitor
sleep 3

print_info "Starting Kopano Monitoring Service"
kopano-monitor "${MONITOR_ADDITIONAL_ARGS}" -F
