#!/usr/bin/with-contenv bash

SPAMD_FILES_HAM_PATH=${SPAMD_FILES_HAM_PATH:-"/data/spamd/ham"}
SPAMD_FILES_SPAM_PATH=${SPAMD_FILES_SPAM_PATH:-"/data/spamd/spam"}
SPAMD_SA_GROUP=${SPAMD_SA_GROUP:-"kopano"}
SPAMD_SSL_CERT_FILE=${SPAMD_SSL_CERT_FILE:-"/certs/core/spamd.crt"}
SPAMD_SSL_KEY_FILE=${SPAMD_SSL_KEY_FILE:-"/certs/core/spamd.pem"}