#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service

PROCESS_NAME="kopano"

mkdir -p ${CONFIG_PATH}
sanity_var INSTALL_ID "Installation ID"
configure_install_id
configure_logging
## Don't Bother with changing mode - Not working
case "$MODE" in
	"STANDALONE")
		print_info "Preparing to setup (AIO) Kopano Services"
		sanity_db
		db_ready mariadb
		create_user_scripts
		create_quota_templates
		configure_cron_purge_deleted
		configure_autorespond
		configure_backup
		configure_calendar
		configure_dagent
		configure_gateway
		configure_ical
		configure_kdav
        configure_meet
		configure_monitor
		configure_search
		configure_server
		configure_spamd
		configure_spooler
		configure_user_backend
		configure_webapp
		configure_webapp_plugins
		configure_zpush
		create_user_scripts
		create_quota_templates
		move_remaining_config
        print_info "Container Iniitalization Complete"
    ;;
	"CALENDAR" | "calendar" )
		print_info "Preparing to setup standalone Kopano Calendar Service"
        #service_stop 30-kopano-server
        service_stop 31-kopano-spooler
        service_stop 32-kopano-gateway
        service_stop 33-kopano-dagent
        service_stop 34-kopano-ical
        service_stop 35-kopano-spamd
        service_stop 36-kopano-search
        service_stop 37-kopano-monitor
		configure_calendar
		configure_server
	;;
	"DAGENT" | "dagent" )
		print_info "Preparing to setup standalone Kopano DAgent Service"
		service_stop 10-nginx
		service_stop 11-nginx-config-reload
		service_stop 20-php-fpm
        service_stop 30-kopano-server
        service_stop 31-kopano-spooler
        service_stop 32-kopano-gateway
        service_stop 34-kopano-ical
        service_stop 35-kopano-spamd
        service_stop 36-kopano-search
        service_stop 37-kopano-monitor
		configure_dagent
	;;
	"GATEWAY" | "gateway" )
		print_info "Preparing to setup standalone Kopano Gateway Service"
		service_stop 10-nginx
		service_stop 11-nginx-config-reload
		service_stop 20-php-fpm
		configure_gateway
	;;
	"ICAL" | "ical" )
		print_info "Preparing to setup standalone Kopano ICAL Service"
		service_stop 10-nginx
		service_stop 11-nginx-config-reload
		service_stop 20-php-fpm
		configure_ical
	;;
	"KDAV" | "kdav" )
        print_info "Preparing to setup standalone Nginx Webservice"
        service_stop 30-kopano-server
        service_stop 31-kopano-spooler
        service_stop 32-kopano-gateway
        service_stop 33-kopano-dagent
        service_stop 34-kopano-ical
        service_stop 35-kopano-spamd
        service_stop 36-kopano-search
        service_stop 37-kopano-monitor
        configure_kdav
    ;;
	"MEET" | "meet" )
		print_info "Preparing to setup standalone Kopano Meet Service"
        #service_stop 30-kopano-server
        service_stop 31-kopano-spooler
        service_stop 32-kopano-gateway
        service_stop 33-kopano-dagent
        service_stop 34-kopano-ical
        service_stop 35-kopano-spamd
        service_stop 36-kopano-search
        service_stop 37-kopano-monitor
		configure_meet
		configure_server
	;;
	"MONITOR" | "monitor" )
		print_info "Preparing to setup standalone Kopano Monitor Service"
		service_stop 10-nginx
		service_stop 11-nginx-config-reload
		service_stop 20-php-fpm
		configure_monitor
		create_quota_templates
	;;
	"SEARCH" | "search" )
		print_info "Preparing to setup standalone Kopano Search Service"
		service_stop 10-nginx
		service_stop 11-nginx-config-reload		
		service_stop 20-php-fpm
		configure_search
	;;
	"SERVER" | "server" )
		print_info "Preparing to setup standalone Kopano Server Service"
		configure_cron_ldap_sync
		configure_cron_purge_deleted
		create_user_scripts
		service_stop 10-nginx
		service_stop 11-nginx-config-reload
		service_stop 20-php-fpm
		configure_server	
	;;
	"SPAMD" | "spamd" )
		print_info "Preparing to setup standalone Kopano SpamD Service"
		service_stop 10-nginx
		service_stop 11-nginx-config-reload
		service_stop 20-php-fpm
		configure_spamd
	;;
	"SPOOLER" | "spooler" )
		print_info "Preparing to setup standalone Kopano Spooler Service"
		service_stop 10-nginx
		service_stop 11-nginx-config-reload
		service_stop 20-php-fpm
		configure_spooler				
	;;
	"WEBSERVER" | "webserver" | "web" )
        print_info "Preparing to setup standalone Nginx Webservice"
		configure_kdav
		configure_webapp
		configure_webapp_plugins
		configure_zpush
        service_stop 30-kopano-server
        service_stop 31-kopano-spooler
        service_stop 32-kopano-gateway
        service_stop 33-kopano-dagent
        service_stop 34-kopano-ical
        service_stop 35-kopano-spamd
        service_stop 36-kopano-search
        service_stop 37-kopano-monitor
    ;;
	"ZPUSH" | "zpush" )
        print_info "Preparing to setup standalone Nginx Webservice"
		configure_zpush
        service_stop 30-kopano-server
        service_stop 31-kopano-spooler
        service_stop 32-kopano-gateway
        service_stop 33-kopano-dagent
        service_stop 34-kopano-ical
        service_stop 35-kopano-spamd
        service_stop 36-kopano-search
        service_stop 37-kopano-monitor
    ;;
esac

liftoff
