#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service functions kopano

PROCESS_NAME="kopano-migrator"
check_container_initialized
liftoff

rm -rf /var/run/kopano/gateway-migrator.pid

wait_for_server file:///var/run/kopano/server.sock
sleep 3

print_info "Starting Kopano Gateway Migrator Mode"
print_warn "This tool allows access without authentication into users mail stores! Please disable when finisihed"
print_warn "Active ports are 1433 for unencrypted IMAP and 9993 for TLS encrypted IMAP"
kopano-gateway -c /etc/kopano/migrator.cfg "${GATEWAY_ADDITIONAL_ARGS}"
