#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service defaults 30-kopano

PROCESS_NAME="kopano-monitor"
check_container_initialized
check_service_initialized 36-kopano-search
liftoff

rm -rf /var/run/kopano/monitor.pid

print_info "Starting Kopano Monitoring Service"
kopano-monitor ${MONITOR_ADDITIONAL_ARGS}
