#!/usr/bin/with-contenv bash

source /assets/functions/00-container
source /assets/defaults/kopano-server
prepare_service functions kopano
PROCESS_NAME="post-startup-routines"
check_container_initialized
check_service_initialized 41-kopano-server
liftoff

wait_for_server
sleep 3

create_store

if [ "$SERVER_USER_PLUGIN" = "LDAP" ] || [ "$SERVER_USER_PLUGIN" = "ldap" ] ; then
	print_info "Performing Initial Container Start LDAP Sync"
	sleep 10
	silent kopano-admin --sync
fi

s6-svc -d /var/run/s6/services/90-post-server-startup-routines
