---

# OpenID Connect client registry.
clients:
#  - id: oidc-client-example.js
#    name: OIDC Playground
#    application_type: web
#    redirect_uris:
#       - https://devmail.kopano.com/kapi-playground/
#  - id: playground.js
#    name: OIDC Playground
#    application_type: web
#    redirect_uris:
#       - https://my-host:8509/

#  - id: playground-trusted.js
#    name: Trusted OIDC Playground
#    trusted: yes
#    application_type: web
#    redirect_uris:
#       - https://my-host:8509/

#  - id: playground-trusted.js
#    name: Trusted Insecure OIDC Playground
#    trusted: yes
#    application_type: web
#    insecure: yes

#  - id: client-with-keys
#    secret: super
#    application_type: native
#    redirect_uris:
#      - http://localhost
#    jwks:
#      keys:
#        - kty: EC
#          use: sig
#          kid: client-with-keys-key-1
#          crv: P-256
#          x: RTZpWoRbjwX1YavmSHVBj6Cy3Yzdkkp6QLvTGB22D0c
#          y: jeavjwcX0xlDSchFcBMzXSU7wGs2VPpNxWCwmxFvmF0
#    request_object_signing_alg: ES256

#  - id: first
#    secret: lala
#    application_type: native
#    redirect_uris:
#      - my://app

#  - id: second
#    secret: lulu
#    application_type: native
#    redirect_uris:
#      - http://localhost
