#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service functions 30-kopano

PROCESS_NAME="kopano-gateway"
check_container_initialized
check_service_initialized 31-kopano-spooler
liftoff

rm -rf /var/run/kopano/gateway.pid

wait_for_server

print_info "Starting Kopano Gateway"
kopano-gateway ${GATEWAY_ADDITIONAL_ARGS}
