#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service functions kopano
PROCESS_NAME="kopano-kdav-apache"
check_container_initialized
liftoff

print_info "Starting Apache for Kopano KDAV on port 8888"
silent httpd -DFOREGROUND