#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service defaults 30-kopano

PROCESS_NAME="kopano-server"
check_container_initialized
check_service_initialized init 30-kopano
liftoff

rm -rf /var/run/kopano/server.pid

print_info "Starting Kopano Server"
kopano-server ${SERVER_ADDITIONAL_ARGS}
