#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service both 30-kopano

PROCESS_NAME="kopano-kwm"
check_container_initialized
check_service_initialized 30-kopano-server
liftoff

parse_config ${CONFIG_PATH}${KWM_CONFIG_FILE}

## Defaults
default_oidc_issuer_identifier=https://localhost
default_admin_tokens_secret_key_file=/certs/kwm-tokens-secret.key
default_turn_service_url=https://turnauth.kopano.com/turnserverauth/
default_registration_conf_file=/etc/kopano/kwmserverd-registration.yaml


if [ -z "$oidc_issuer_identifier" ]; then
	oidc_issuer_identifier=${OIDC_ISSUER_IDENTIFIER:-${default_oidc_issuer_identifier}}
fi

## TLS Verify
if [ "$insecure" = "yes" ]; then
	set -- "$@" "--insecure"
fi

## Interface Setup
if [ -n "$listen" ]; then
	set -- "$@" --listen="$listen"
fi

## Logging
if [ -n "$log_level" ]; then
	set -- "$@" --log-level="$log_level"
fi

## OIDC
if [ -n "$oidc_issuer_identifier" ]; then
	set -- "$@" --iss="$oidc_issuer_identifier"
fi

## API
if [ -z "$enable_rtm_api" -o "$enable_rtm_api" = "yes" ]; then
	set -- "$@" --enable-rtm-api
fi

if [ "$enable_mcu_api" = "yes" ]; then
	set -- "$@" --enable-mcu-api
fi

if [ "$enable_guest_api" = "yes" ]; then
	set -- "$@" --enable-guest-api
fi

## Authentication
if [ -n "$rtm_required_scopes" ]; then
	for scope in $rtm_required_scopes; do
		set -- "$@" --rtm-required-scope="$scope"
	done
fi

if [ -z "$admin_tokens_secret_key" -a -f "${default_admin_tokens_secret_key_file}" ]; then
	admin_tokens_secret_key="${default_admin_tokens_secret_key_file}"
fi
if [ -n "$admin_tokens_secret_key" ]; then
	set -- "$@" --admin-tokens-key="$admin_tokens_secret_key"
fi

if [ -z "$registration_conf" ]; then
	if [ -f "${default_registration_conf_file}" ]; then
		registration_conf="${default_registration_conf_file}"
	fi
fi
if [ -n "$registration_conf" ]; then
	set -- "$@" --registration-conf="$registration_conf"
fi

## Turn
if [ -z "$turn_service_url" ]; then
	turn_service_url=${default_turn_service_url}
fi
if [ -n "$turn_service_url" ]; then
	set -- "$@" --turn-service-url="$turn_service_url"
fi

if [ -n "$turn_service_credentials" ]; then
	set -- "$@" --turn-service-credentials="$turn_service_credentials"
fi

if [ -n "$turn_server_shared_secret" ]; then
	set -- "$@" --turn-server-shared-secret="$turn_server_shared_secret"
fi

if [ -n "$turn_uris" ]; then
	for uri in $turn_uris; do
		set -- "$@" --turn-uri="$uri"
	done
fi

## Guest Access
if [ "$allow_guest_only_channels" = "yes" ]; then
	set -- "$@" --allow-guest-only-channels
fi

if [ -n "$public_guest_access_regexp" ]; then
	set -- "$@" --public-guest-access-regexp="$public_guest_access_regexp"
fi

print_info "Starting Kopano KWM Service"
if [ "${LOG_TYPE}" = "FILE" ] || [ "${LOG_TYPE}" = "file" ] ; then
	if [ "${LOG_FILE_KWM}" = "/dev/null" ] ; then unset ${LOG_PATH_KOPANO} ; fi;
	/usr/libexec/kopano/kwmserverd serve "$@" 2>> ${LOG_PATH_KOPANO}${LOG_FILE_KWM}
else
	/usr/libexec/kopano/kwmserverd serve "$@"
fi
