
# Manual Workflow (Application)

name: latest_manual

on:
  workflow_dispatch:
    inputs:
      Manual Build:
        description: 'Manual Build of Latest Sources (untagged)'
        required: false
jobs:
  php80_debian_buster_latest:
    env:
      PHP_VERSION: "8.0"
      DISTRO: "debian"
      DISTRO_VARIANT: "buster"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=${GITHUB_REPOSITORY/docker-/}
          set -x
          if [[ $GITHUB_REF == refs/heads/* ]]; then
             if [[ $GITHUB_REF == refs/heads/*/* ]] ; then
               BRANCH="${DOCKER_IMAGE}:$(echo $GITHUB_REF | sed "s|refs/heads/||g" | sed "s|/|-|g")"
             else
               BRANCH=${GITHUB_REF#refs/heads/}
             fi

            case ${BRANCH} in
              "main" | "master" )
                  ## Irrelevant
                  BRANCHTAG="${DOCKER_IMAGE}:debian-php${PHP_VERSION},${DOCKER_IMAGE}:debian-php${PHP_VERSION}-${DISTRIB}"
                ;;
              "develop" )
                  ## Irrelevant
                  BRANCHTAG="${DOCKER_IMAGE}:develop"
                ;;
              * )
                  BRANCHTAG="${DOCKER_IMAGE}:${DISTRO}-${DISTRO_VARIANT}-php${PHP_VERSION}-kc${BRANCH}-latest"
                ;;
            esac
          fi

          TAGS="${BRANCHTAG}"


          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=docker_image::${DOCKER_IMAGE}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Label
        id: Label
        run: |
          if [ -f "Dockerfile" ] ; then
            sed -i "/FROM .*/a LABEL tiredofit.kopano-core.git_repository=\"https://github.com/${GITHUB_REPOSITORY}\"" Dockerfile
            sed -i "/FROM .*/a LABEL tiredofit.nginx-php-fpm.runtime_version=\"${PHP_VERSION}\"" Dockerfile
            sed -i "/FROM .*/a LABEL tiredofit.nginx-php-fpm.distro=\"${DISTRO_VARIANT}\"" Dockerfile
            sed -i "/FROM .*/a LABEL tiredofit.kopano-core.version=\"${BRANCH}\"" Dockerfile
            sed -i "/FROM .*/a LABEL tiredofit.kopano-core.git_commit=\"${GITHUB_SHA}\"" Dockerfile
            sed -i "/FROM .*/a LABEL tiredofit.kopano-core.git_committed_by=\"${GITHUB_ACTOR}\"" Dockerfile
            sed -i "/FROM .*/a LABEL tiredofit.kopano-core.image_build_date=\"$(date +'%Y-%m-%d %H:%M:%S')\"" Dockerfile
            if [ -f "CHANGELOG.md" ] ; then
              sed -i "/FROM .*/a LABEL tiredofit.kopano-core.git_changelog_version=\"$(head -n1 ./CHANGELOG.md | awk '{print $2}')\"" Dockerfile
              mkdir -p install/assets/.changelogs ; cp CHANGELOG.md install/assets/.changelogs/${GITHUB_REPOSITORY/\//_}.md
            fi

            echo "Kopano Core ${KOPANO_VERSION} latest commit from ${BRANCH} branch" >> install/assets/.changelogs/kopano-core-latest.md
          fi

      - name: Switch
        id: Switch
        run: |
          sed -i "s|FROM docker.io/tiredofit/nginx-php-fpm:${DISTRO}-.* as|FROM docker.io/tiredofit/nginx-php-fpm:${DISTRO}-${PHP_VERSION}-${DISTRO_VARIANT} as|g" Dockerfile
      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.prep.outputs.tags }}

  php74_debian_buster_latest:
    env:
      PHP_VERSION: "7.4"
      DISTRO: "debian"
      DISTRO_VARIANT: "buster"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=${GITHUB_REPOSITORY/docker-/}
          set -x
          if [[ $GITHUB_REF == refs/heads/* ]]; then
             if [[ $GITHUB_REF == refs/heads/*/* ]] ; then
               BRANCH="${DOCKER_IMAGE}:$(echo $GITHUB_REF | sed "s|refs/heads/||g" | sed "s|/|-|g")"
             else
               BRANCH=${GITHUB_REF#refs/heads/}
             fi

            case ${BRANCH} in
              "main" | "master" )
                  ## Irrelevant
                  BRANCHTAG="${DOCKER_IMAGE}:debian-php${PHP_VERSION},${DOCKER_IMAGE}:debian-php${PHP_VERSION}-${DISTRIB}"
                ;;
              "develop" )
                  ## Irrelevant
                  BRANCHTAG="${DOCKER_IMAGE}:develop"
                ;;
              * )
                  BRANCHTAG="${DOCKER_IMAGE}:${DISTRO}-${DISTRO_VARIANT}-php${PHP_VERSION}-kc${BRANCH}-latest"
                ;;
            esac
          fi

          TAGS="${BRANCHTAG}"

          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=docker_image::${DOCKER_IMAGE}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Label
        id: Label
        run: |
          if [ -f "Dockerfile" ] ; then
            sed -i "/FROM .*/a LABEL tiredofit.kopano-core.git_repository=\"https://github.com/${GITHUB_REPOSITORY}\"" Dockerfile
            sed -i "/FROM .*/a LABEL tiredofit.nginx-php-fpm.runtime_version=\"${PHP_VERSION}\"" Dockerfile
            sed -i "/FROM .*/a LABEL tiredofit.nginx-php-fpm.distro=\"${DISTRO_VARIANT}\"" Dockerfile
            sed -i "/FROM .*/a LABEL tiredofit.kopano-core.version=\"${BRANCH}\"" Dockerfile
            sed -i "/FROM .*/a LABEL tiredofit.kopano-core.git_commit=\"${GITHUB_SHA}\"" Dockerfile
            sed -i "/FROM .*/a LABEL tiredofit.kopano-core.git_committed_by=\"${GITHUB_ACTOR}\"" Dockerfile
            sed -i "/FROM .*/a LABEL tiredofit.kopano-core.image_build_date=\"$(date +'%Y-%m-%d %H:%M:%S')\"" Dockerfile
            if [ -f "CHANGELOG.md" ] ; then
              sed -i "/FROM .*/a LABEL tiredofit.kopano-core.git_changelog_version=\"$(head -n1 ./CHANGELOG.md | awk '{print $2}')\"" Dockerfile
              mkdir -p install/assets/.changelogs ; cp CHANGELOG.md install/assets/.changelogs/${GITHUB_REPOSITORY/\//_}.md
            fi

            echo "Kopano Core ${KOPANO_VERSION} latest commit from ${BRANCH} branch" >> install/assets/.changelogs/kopano-core-latest.md
          fi

      - name: Switch
        id: Switch
        run: |
          sed -i "s|FROM docker.io/tiredofit/nginx-php-fpm:${DISTRO}-.* as|FROM docker.io/tiredofit/nginx-php-fpm:${DISTRO}-${PHP_VERSION}-${DISTRO_VARIANT} as|g" Dockerfile
      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.prep.outputs.tags }}


  php73_debian_buster_latest:
    env:
      PHP_VERSION: "7.3"
      DISTRO: "debian"
      DISTRO_VARIANT: "buster"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=${GITHUB_REPOSITORY/docker-/}
          set -x
          if [[ $GITHUB_REF == refs/heads/* ]]; then
             if [[ $GITHUB_REF == refs/heads/*/* ]] ; then
               BRANCH="${DOCKER_IMAGE}:$(echo $GITHUB_REF | sed "s|refs/heads/||g" | sed "s|/|-|g")"
             else
               BRANCH=${GITHUB_REF#refs/heads/}
             fi

            case ${BRANCH} in
              "main" | "master" )
                  ## Irrelevant
                  BRANCHTAG="${DOCKER_IMAGE}:debian-php${PHP_VERSION},${DOCKER_IMAGE}:debian-php${PHP_VERSION}-${DISTRIB}"
                ;;
              "develop" )
                  ## Irrelevant
                  BRANCHTAG="${DOCKER_IMAGE}:develop"
                ;;
              * )
                  BRANCHTAG="${DOCKER_IMAGE}:${DISTRO}-${DISTRO_VARIANT}-php${PHP_VERSION}-kc${BRANCH}-latest"
                ;;
            esac
          fi

          TAGS="${BRANCHTAG}"

          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=docker_image::${DOCKER_IMAGE}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Label
        id: Label
        run: |
          if [ -f "Dockerfile" ] ; then
            sed -i "/FROM .*/a LABEL tiredofit.kopano-core.git_repository=\"https://github.com/${GITHUB_REPOSITORY}\"" Dockerfile
            sed -i "/FROM .*/a LABEL tiredofit.nginx-php-fpm.runtime_version=\"${PHP_VERSION}\"" Dockerfile
            sed -i "/FROM .*/a LABEL tiredofit.nginx-php-fpm.distro=\"${DISTRO_VARIANT}\"" Dockerfile
            sed -i "/FROM .*/a LABEL tiredofit.kopano-core.version=\"${BRANCH}\"" Dockerfile
            sed -i "/FROM .*/a LABEL tiredofit.kopano-core.git_commit=\"${GITHUB_SHA}\"" Dockerfile
            sed -i "/FROM .*/a LABEL tiredofit.kopano-core.git_committed_by=\"${GITHUB_ACTOR}\"" Dockerfile
            sed -i "/FROM .*/a LABEL tiredofit.kopano-core.image_build_date=\"$(date +'%Y-%m-%d %H:%M:%S')\"" Dockerfile
            if [ -f "CHANGELOG.md" ] ; then
              sed -i "/FROM .*/a LABEL tiredofit.kopano-core.git_changelog_version=\"$(head -n1 ./CHANGELOG.md | awk '{print $2}')\"" Dockerfile
              mkdir -p install/assets/.changelogs ; cp CHANGELOG.md install/assets/.changelogs/${GITHUB_REPOSITORY/\//_}.md
            fi

            echo "Kopano Core ${KOPANO_VERSION} latest commit from ${BRANCH} branch" >> install/assets/.changelogs/kopano-core-latest.md
          fi

      - name: Switch
        id: Switch
        run: |
          sed -i "s|FROM docker.io/tiredofit/nginx-php-fpm:${DISTRO}-.* as|FROM docker.io/tiredofit/nginx-php-fpm:${DISTRO}-${PHP_VERSION}-${DISTRO_VARIANT} as|g" Dockerfile
      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.prep.outputs.tags }}
